name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install react scripts for build
        run: npm install react-scripts

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
