name: Deploy

on:
  push:
    branches: [ main ]

env:
  REACT_APP_ROOT_FOLDER_ID: ${{ vars.REACT_APP_ROOT_FOLDER_ID }}
  REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}

jobs:
  deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display env vars (based on github actions vars)
        run: |
          echo $REACT_APP_ROOT_FOLDER_ID
          echo $REACT_APP_API_BASE_URL

      - name: Install react scripts for build
        run: npm install react-scripts

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
